name: CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspaces
        run: |
          pnpm --filter @pkautos/api build || true
          pnpm --filter @pkautos/web-automart build || true
          pnpm --filter @pkautos/web-autotrader build || true

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images (multi-arch)
        run: |
          echo "TODO: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/org/api:dev ./apps/api"

      - name: Trivy scan (TODO)
        run: |
          echo "TODO: trivy image ghcr.io/org/api:dev"

      - name: Unit tests (placeholder)
        run: |
          echo "TODO: run jest"

      - name: Helm lint (TODO)
        run: |
          echo "TODO: helm lint infra/helm/*"

      - name: K8s deploy dev (TODO)
        run: |
          echo "TODO: helm upgrade --install release-name infra/helm/chart --namespace dev"

      - name: Smoke tests
        run: |
          docker compose config
          docker compose up -d api web-automart web-autotrader
          sleep 20
          bash scripts/smoke.sh
          docker compose ps
          docker compose logs --no-color --tail=200
