name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          # caching handled by pnpm/action-setup later; corepack will manage pnpm binary

      - name: Enable corepack & prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Setup pnpm (cache)
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: pnpm store path
        run: pnpm config set store-dir .pnpm-store

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: API unit/e2e tests
        working-directory: apps/api
        run: pnpm --filter @pkautos/api test || npm test

      - name: API OTel span test (in-memory)
        working-directory: apps/api
        env:
          OTEL_TEST_EXPORTER: inmemory
        run: pnpm --filter @pkautos/api test -- otel-demo.e2e.spec.ts || pnpm test -- otel-demo.e2e.spec.ts

      - name: Web automart tests
        working-directory: apps/web-automart
        run: pnpm --filter @pkautos/web-automart test || pnpm test

      - name: Web autotrader tests
        working-directory: apps/web-autotrader
        run: pnpm --filter @pkautos/web-autotrader test || pnpm test

      - name: API coverage
        working-directory: apps/api
        run: pnpm --filter @pkautos/api test:coverage || pnpm test:coverage

      - name: Upload coverage (API)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-api
          path: apps/api/coverage
          if-no-files-found: ignore

      - name: Upload coverage (web-automart)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-web-automart
          path: apps/web-automart/coverage
          if-no-files-found: ignore

      - name: Upload coverage (web-autotrader)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-web-autotrader
          path: apps/web-autotrader/coverage
          if-no-files-found: ignore

      - name: Build docker images (local)
        run: docker compose build api web-automart web-autotrader

      - name: Spin up stack
        run: |
          docker compose up -d api web-automart web-autotrader
          echo 'Waiting for services (smoke test with retries)...'
          SMOKE_MAX_ATTEMPTS=30 SMOKE_SLEEP_SECONDS=2 bash scripts/smoke.sh

      - name: Show container logs (on failure)
        if: failure()
        run: docker compose logs --no-color

      - name: Upload container logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: |
            $(pwd)/docker-compose.yml
            $(pwd)/.github/workflows/ci.yml
            $(pwd)/scripts/smoke.sh
          if-no-files-found: ignore

      - name: Cleanup stack
        if: always()
        run: |
          docker compose ps
          docker compose down -v

  trivy-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          vuln-type: 'os,library'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
